name: cut-release

on:
  push:
    tags:
      - "v*"

concurrency: cut-release

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for pushing the images to ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3

      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3
        with:
          go-version-file: './go.mod'
          check-latest: true

      - uses: sigstore/cosign-installer@b3413d484cc23cf8778c3d2aa361568d4eb54679 # v2
      - uses: anchore/sbom-action/download-syft@b5042e9d19d8b32849779bfe17673ff84aec702d # v0.11.0
      - uses: imjasonh/setup-ko@78eea08f10db87a7a23a666a4a6fe2734f2eeb8d # v0.4

      - uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v3
        with:
          install-only: true

      - name: release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
